[client]
toolbarMode = "minimal"
showErrorDetails = false

[ui]
hideSidebarNav = true
hideTopBar = true

[theme]
base="dark"
primaryColor = "#dab07b"
backgroundColor = "#341645"
secondaryBackgroundColor = "#250f31"
textColor = "#fcfaff"
font = "sans serif"
